package com.newsmvpdemo.local.table;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WELFARE_INFO".
*/
public class WelfareInfoDao extends AbstractDao<WelfareInfo, String> {

    public static final String TABLENAME = "WELFARE_INFO";

    /**
     * Properties of entity WelfareInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Url = new Property(0, String.class, "url", true, "URL");
        public final static Property Id = new Property(1, String.class, "id", false, "ID");
        public final static Property CreatedAt = new Property(2, String.class, "createdAt", false, "CREATED_AT");
        public final static Property Desc = new Property(3, String.class, "desc", false, "DESC");
        public final static Property PublishedAt = new Property(4, String.class, "publishedAt", false, "PUBLISHED_AT");
        public final static Property Source = new Property(5, String.class, "source", false, "SOURCE");
        public final static Property Type = new Property(6, String.class, "type", false, "TYPE");
        public final static Property Used = new Property(7, boolean.class, "used", false, "USED");
        public final static Property Who = new Property(8, String.class, "who", false, "WHO");
        public final static Property IsLove = new Property(9, boolean.class, "isLove", false, "IS_LOVE");
        public final static Property IsPraise = new Property(10, boolean.class, "isPraise", false, "IS_PRAISE");
        public final static Property IsDownload = new Property(11, boolean.class, "isDownload", false, "IS_DOWNLOAD");
        public final static Property Pixel = new Property(12, String.class, "pixel", false, "PIXEL");
    }


    public WelfareInfoDao(DaoConfig config) {
        super(config);
    }
    
    public WelfareInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WELFARE_INFO\" (" + //
                "\"URL\" TEXT PRIMARY KEY NOT NULL ," + // 0: url
                "\"ID\" TEXT," + // 1: id
                "\"CREATED_AT\" TEXT," + // 2: createdAt
                "\"DESC\" TEXT," + // 3: desc
                "\"PUBLISHED_AT\" TEXT," + // 4: publishedAt
                "\"SOURCE\" TEXT," + // 5: source
                "\"TYPE\" TEXT," + // 6: type
                "\"USED\" INTEGER NOT NULL ," + // 7: used
                "\"WHO\" TEXT," + // 8: who
                "\"IS_LOVE\" INTEGER NOT NULL ," + // 9: isLove
                "\"IS_PRAISE\" INTEGER NOT NULL ," + // 10: isPraise
                "\"IS_DOWNLOAD\" INTEGER NOT NULL ," + // 11: isDownload
                "\"PIXEL\" TEXT);"); // 12: pixel
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WELFARE_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WelfareInfo entity) {
        stmt.clearBindings();
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(1, url);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
 
        String createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindString(3, createdAt);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(4, desc);
        }
 
        String publishedAt = entity.getPublishedAt();
        if (publishedAt != null) {
            stmt.bindString(5, publishedAt);
        }
 
        String source = entity.getSource();
        if (source != null) {
            stmt.bindString(6, source);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(7, type);
        }
        stmt.bindLong(8, entity.getUsed() ? 1L: 0L);
 
        String who = entity.getWho();
        if (who != null) {
            stmt.bindString(9, who);
        }
        stmt.bindLong(10, entity.getIsLove() ? 1L: 0L);
        stmt.bindLong(11, entity.getIsPraise() ? 1L: 0L);
        stmt.bindLong(12, entity.getIsDownload() ? 1L: 0L);
 
        String pixel = entity.getPixel();
        if (pixel != null) {
            stmt.bindString(13, pixel);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WelfareInfo entity) {
        stmt.clearBindings();
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(1, url);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
 
        String createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindString(3, createdAt);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(4, desc);
        }
 
        String publishedAt = entity.getPublishedAt();
        if (publishedAt != null) {
            stmt.bindString(5, publishedAt);
        }
 
        String source = entity.getSource();
        if (source != null) {
            stmt.bindString(6, source);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(7, type);
        }
        stmt.bindLong(8, entity.getUsed() ? 1L: 0L);
 
        String who = entity.getWho();
        if (who != null) {
            stmt.bindString(9, who);
        }
        stmt.bindLong(10, entity.getIsLove() ? 1L: 0L);
        stmt.bindLong(11, entity.getIsPraise() ? 1L: 0L);
        stmt.bindLong(12, entity.getIsDownload() ? 1L: 0L);
 
        String pixel = entity.getPixel();
        if (pixel != null) {
            stmt.bindString(13, pixel);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public WelfareInfo readEntity(Cursor cursor, int offset) {
        WelfareInfo entity = new WelfareInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // url
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // createdAt
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // desc
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // publishedAt
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // source
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // type
            cursor.getShort(offset + 7) != 0, // used
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // who
            cursor.getShort(offset + 9) != 0, // isLove
            cursor.getShort(offset + 10) != 0, // isPraise
            cursor.getShort(offset + 11) != 0, // isDownload
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // pixel
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WelfareInfo entity, int offset) {
        entity.setUrl(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCreatedAt(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDesc(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPublishedAt(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSource(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setType(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUsed(cursor.getShort(offset + 7) != 0);
        entity.setWho(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setIsLove(cursor.getShort(offset + 9) != 0);
        entity.setIsPraise(cursor.getShort(offset + 10) != 0);
        entity.setIsDownload(cursor.getShort(offset + 11) != 0);
        entity.setPixel(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    @Override
    protected final String updateKeyAfterInsert(WelfareInfo entity, long rowId) {
        return entity.getUrl();
    }
    
    @Override
    public String getKey(WelfareInfo entity) {
        if(entity != null) {
            return entity.getUrl();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WelfareInfo entity) {
        return entity.getUrl() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
